version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/static:/app/static

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"